// Copyright 2022 Stefan Kerkmann
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include "config_common.h"

#define DIODE_DIRECTION COL2ROW

#define QMK_WAITING_TEST_BUSY_PIN GP28
#define QMK_WAITING_TEST_YIELD_PIN GP29

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define MATRIX_ROWS 10
#define MATRIX_COLS 5

#define MATRIX_ROW_PINS { GP0, GP1, GP2, GP3, GP4 }
#define MATRIX_COL_PINS { GP5, GP6, GP7, GP8, GP9 }

#define MASTER_RIGHT
// #define MASTER_LEFT

#define SERIAL_USART_DRIVER SIOD0
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13

#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP19
#define POINTING_DEVICE_CS_PIN GP10
// #define POINTING_DEVICE_MOTION_PIN GP26
#define PMW33XX_LIFTOFF_DISTANCE 0b1111
#define ROTATIONAL_TRANSFORM_ANGLE -95
#define POINTING_DEVICE_INVERT_X
#define PMW33XX_CPI 1000

#define COMBO_COUNT 1
